import Head from 'next/head'
import Image from 'next/image'


const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

export default function Home() {
  return (
    <div>
    <Head>
      <title>Weather - Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
   </div>
  )
}
